// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKho.Data.Context;

namespace QuanLyKho.Data.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20221124144158_create_db")]
    partial class create_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuanLyKho.Data.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "THỊT, CÁ, TRỨNG, HẢI SẢN",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4540)
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "RAU, CỦ, TRÁI CÂY",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4595)
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "THỰC PHẨM ĐÔNG - MÁT",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4597)
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "MÌ, MIẾN, CHÁO, PHỞ",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4599)
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "GẠO, BỘT, ĐỒ KHÔ",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4600)
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "DẦU ĂN, NƯỚC CHẤM, GIA VỊ",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4601)
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "BIA, NƯỚC GIẢI KHÁT",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4603)
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "SỮA CÁC LOẠI",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4605)
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "BÁNH KẸO CÁC LOẠI",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4606)
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "CHĂM SÓC CÁ NHÂN",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4608)
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "SẢN PHẨM CHO MẸ VÀ BÉ",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4609)
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "VỆ SINH NHÀ CỬA",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4611)
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "ĐỒ DÙNG GIA ĐÌNH",
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 754, DateTimeKind.Local).AddTicks(4612)
                        });
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhaCungCap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhaCungCap");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 764, DateTimeKind.Local).AddTicks(1688),
                            DiaChi = "Lô A4- Đường NB, Cụm Nhị Xuân, X. Xuân Thới Sơn, H. Hóc Môn Tp. Hồ Chí Minh (TPHCM)",
                            Email = "cd@congdanh.vn",
                            NguoiDaiDien = "Ngô Bình An",
                            SoDienThoai = "0908 838 848",
                            TenNhaCungCap = "Thực Phẩm Công Danh - Công Ty TNHH MTV SX TM Thực Phẩm Công Danh"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 764, DateTimeKind.Local).AddTicks(1775),
                            DiaChi = "368/4 Tỉnh Lộ 15, Ấp Bến Cỏ, X. Phú Hòa Đông, H. Củ Chi, Tp. Hồ Chí Minh (TPHCM)",
                            Email = "duyanhfoodscuchi@gmail.com",
                            NguoiDaiDien = "Trần Phú Ân",
                            SoDienThoai = "0903 646 487",
                            TenNhaCungCap = "Thực Phẩm Duy Anh - Công Ty TNHH Xuất Nhập Khẩu Thực Phẩm Duy Anh"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 764, DateTimeKind.Local).AddTicks(1778),
                            DiaChi = "Khu Công Nghiệp Cát Lái, 934D1 Đường D, P. Thạnh Mỹ Lợi, Q. 2, Tp. Hồ Chí Minh (TPHCM), Việt Nam",
                            Email = "phongkinhdoanh@gasaco.com.vn",
                            NguoiDaiDien = "Nguyễn Ðức Bảo",
                            SoDienThoai = "(028) 37421343",
                            TenNhaCungCap = "Công Ty TNHH Chế Biến Thực Phẩm Nước Giải Khát Quang Minh"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 764, DateTimeKind.Local).AddTicks(1821),
                            DiaChi = "E4/20 Nguyễn Hữu Trí, Thị Trấn Tân Túc, Huyện Bình Chánh, Tp. Hồ Chí Minh (TPHCM), Việt Nam",
                            Email = "tmdt@nosafood.com",
                            NguoiDaiDien = "Nguyễn Vinh Diệu",
                            SoDienThoai = "0972 333 601",
                            TenNhaCungCap = "Gia Vị Nosafood - Công Ty Cổ Phần Nosafood"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 764, DateTimeKind.Local).AddTicks(1823),
                            DiaChi = "216R Quang Trung, P. 10, Q. Gò Vấp, Tp. Hồ Chí Minh (TPHCM), Việt Nam",
                            Email = "info@oriflame.com.vn",
                            NguoiDaiDien = "Lê Gia Ðức ",
                            SoDienThoai = "0975 559 016",
                            TenNhaCungCap = "Công Ty TNHH Oriflame Việt Nam"
                        });
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(4723),
                            ProductName = "Thịt ba rọi bò Thảo Tiến Foods khay 300g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(5955),
                            ProductName = "Ba rọi heo C.P khay 500g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(5998),
                            ProductName = "Ức gà tươi phi lê C.P khay 500g (1-3 miếng)",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6000),
                            ProductName = "Tôm thẻ nguyên con khay 250g (10 - 13 con)",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6001),
                            ProductName = "Cá hồi đông lạnh cắt khúc khay 300g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6006),
                            ProductName = "Hộp 10 trứng gà tươi 4KFarm",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6024),
                            ProductName = "Cải bẹ xanh baby gói 300g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6026),
                            ProductName = "Xà lách lolo xanh thủy canh gói 300g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6028),
                            ProductName = "Giá đậu xanh gói 200g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6030),
                            ProductName = "Ớt hiểm trái túi 50g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6032),
                            ProductName = "Tắc trái túi 200g (20 - 21 trái)",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6034),
                            ProductName = "Cà rốt baby vỉ 500g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6035),
                            ProductName = "Khổ qua khay 500g (3-5 trái)",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6036),
                            ProductName = "Khoai lang Nhật túi 1kg (4 - 10 củ)",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6038),
                            ProductName = "Bí đỏ tròn túi 500g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6039),
                            ProductName = "Táo Queen nhập khẩu New Zealand hộp 1kg (5-7 trái)",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6040),
                            ProductName = "Táo Ninh Thuận túi 1kg (25 - 30 trái)",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6043),
                            ProductName = "Bưởi năm roi trái từ 1.3kg - 1.4kg",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6049),
                            ProductName = "Kem que Topten Socola Wall's 55g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6051),
                            ProductName = "2 hộp kem vani sốt socola Wall's 450g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6098),
                            ProductName = "Bánh mì tươi đông lạnh O'smiles 350g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6100),
                            ProductName = "Bánh mì que không nhân Vbread túi 10 cái x 30g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6102),
                            ProductName = "TChả lụa bì ớt xiêm xanh G Kitchen cây 500g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6104),
                            ProductName = "Xúc xích phô mai Kichi Kichi Icook khay 340g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6105),
                            ProductName = "Chả giò hải sản trái cây La Cusina gói 300g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6107),
                            ProductName = "Mực viên Bếp 5 sao gói 200g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6108),
                            ProductName = "Phô mai Vinamilk hộp 120g (8 miếng)",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6110),
                            ProductName = "Sữa uống lên men hương tự nhiên Betagen chai 400ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6111),
                            ProductName = "Kim chi cải thảo cắt lát Bibigo Ông Kim's gói 100g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6113),
                            ProductName = "Ớt ngâm chua ngọt Sông Hương hũ 350g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6117),
                            ProductName = "Thùng 30 gói mì Hảo Hảo tôm chua cay 75g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6119),
                            ProductName = "Thùng 30 gói mì 3 Miền tôm chua cay 65g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6121),
                            ProductName = "Thùng 30 gói mì Kokomi 90 tôm chua cay 90g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6126),
                            ProductName = "Gạo thơm A An ST21 túi 5kg",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 5,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6128),
                            ProductName = "Gạo trắng Thiên Nhật túi 5kg",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 6,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6132),
                            ProductName = "Dầu thực vật Nakydaco Cooking Oil chai 1 lít",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 6,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6134),
                            ProductName = "Đường mía thượng hạng Biên Hòa gói 1kg",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 6,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6136),
                            ProductName = "Bột ngọt hạt lớn Ajinomoto gói 454g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 6,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6137),
                            ProductName = "Muối biển Bạc Liêu cao cấp gói 500g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 6,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6139),
                            ProductName = "Nước mắm Nam Ngư 10 độ đạm chai 900ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 6,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6140),
                            ProductName = "Nước tương đậu nành đậm đặc Maggi chai 700ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 6,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6141),
                            ProductName = "Dầu hào đậm đặc Maggi chai 530g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 7,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6146),
                            ProductName = "Thùng 24 lon bia Sài Gòn Lager 330ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 7,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6148),
                            ProductName = "Thùng 24 lon bia Heineken Sleek 330ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 7,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6149),
                            ProductName = "Rượu soju Good Day vị đào 13.5% chai 360ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 7,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6151),
                            ProductName = "6 lon nước ngọt Coca Cola 235ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 7,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6152),
                            ProductName = "6 chai nước ngọt Sprite hương chanh 390ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 7,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6154),
                            ProductName = "6 lon nước tăng lực Redbull 250ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 7,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6155),
                            ProductName = "6 chai Sting hương dâu 330ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 7,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6156),
                            ProductName = "Đá me hạt mềm Thanh Bình 900g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 7,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6158),
                            ProductName = "Cà phê sữa đá NesCafé nhân đôi sánh quyện 600g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 7,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6159),
                            ProductName = "Cà phê sữa VinaCafé Gold Original 480g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 8,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6163),
                            ProductName = "Thùng 48 hộp sữa tươi có đường Vinamilk 180ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 8,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6164),
                            ProductName = "Thùng 48 hộp sữa tươi tiệt trùng vị tự nhiên TH true MILK Hilo 180ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 9,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6168),
                            ProductName = "Kẹo mút hữu cơ 4 hương vị trái cây Yumearth gói 241g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 9,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6170),
                            ProductName = "Bánh quy kem vị cacao Lotte Sand hộp 315g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 9,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6171),
                            ProductName = "Socola sữa hạnh nhân Bernique hộp 450g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 10,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6176),
                            ProductName = "Khăn ướt Yuniku hương trà xanh gói 20 miếng - giao màu ngẫu nhiên",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 10,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6178),
                            ProductName = "Dầu gội tinh dầu Iron Stone For Men Woody Space 620ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 10,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6179),
                            ProductName = "Dầu gội sạch gàu Clear Men Deep Cleanse sạch sâu 175ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 10,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6180),
                            ProductName = "Sữa tắm bảo vệ khỏi vi khuẩn Lifebuoy 980ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 10,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6182),
                            ProductName = "Kem đánh răng Colgate MaxFresh hương trà xanh 230g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 10,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6183),
                            ProductName = "Bộ 3 bàn chải đánh răng Puri Slim Tips Charcoal siêu mềm",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 10,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6184),
                            ProductName = "Khẩu trang y tế Promask N95 FFP2 5 lớp hộp 20 cái",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 11,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6188),
                            ProductName = "Sữa bột Frisolac Gold số 4 lon 380g",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 11,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6218),
                            ProductName = "Tã quần Huggies Dry size XL 62 miếng (cho bé 12 - 17kg)",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 12,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6222),
                            ProductName = "Bột giặt IZI HOME trắng sáng 3kg",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 12,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6224),
                            ProductName = "Nước rửa chén Lix Vitamin E siêu sạch hương trà xanh can 3.53 lít",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 12,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6226),
                            ProductName = "Nước gel tẩy bồn cầu VIM xanh biển diệt khuẩn hương dịu nhẹ chai 880ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 12,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6227),
                            ProductName = "Nước lau sàn Sunlight tinh dầu thảo mộc hương chanh yuzu và sả ngăn côn trùng túi 3.38 lít",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 13,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6232),
                            ProductName = "Lốc 3 cuộn túi rác đen tự huỷ sinh học Bách Hóa XANH 64x78cm (1kg)",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 13,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6233),
                            ProductName = "Bộ bình ly thuỷ tinh Luminarc Rotterdam Blue 5pcs 350ml",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 13,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6235),
                            ProductName = "Bộ 3 nồi nhôm quai tròn xi bóng t3 nhỏ Kim Hằng Bạch Đằng",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 13,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6237),
                            ProductName = "Bộ 10 đôi đũa gỗ cẩm lai tiện tròn Thanh Tú 25cm",
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 13,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 763, DateTimeKind.Local).AddTicks(6238),
                            ProductName = "Khay đá nhỏ nhựa 10 viên Hofaco HPL04 (giao màu ngẫu nhiên)",
                            UnitOfMeasureId = 1
                        });
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 761, DateTimeKind.Local).AddTicks(4365),
                            StoreCode = "CUAHANG01",
                            StoreName = "Cửa hàng chi nhánh Gò Vấp"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 761, DateTimeKind.Local).AddTicks(4450),
                            StoreCode = "CUAHANG02",
                            StoreName = "Cửa hàng chi nhánh Quận 1"
                        });
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.StoreStock", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StoreId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("StoreStock");
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int?>("ToStoreId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("ToStoreId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.TransactionDetail", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransactionId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("TransactionDetail");
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransactionType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 751, DateTimeKind.Local).AddTicks(1655),
                            TransactionTypeName = "Nhập kho"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 752, DateTimeKind.Local).AddTicks(3318),
                            TransactionTypeName = "Xuất kho"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 752, DateTimeKind.Local).AddTicks(3364),
                            TransactionTypeName = "Chuyển hàng"
                        });
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Isocode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("UnitOfMeasureName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasure");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 753, DateTimeKind.Local).AddTicks(8462),
                            Isocode = "sp",
                            UnitOfMeasureName = "Sản phẩm"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 753, DateTimeKind.Local).AddTicks(8724),
                            Isocode = "kg",
                            UnitOfMeasureName = "Kilôgram"
                        });
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("cmnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 760, DateTimeKind.Local).AddTicks(8108),
                            Email = "admin@admin.com",
                            Name = "Admin",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            Surname = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 760, DateTimeKind.Local).AddTicks(8742),
                            Email = "TranHuuThong@gmail.com",
                            Name = "Thống",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            Surname = "Trần Hữu",
                            cmnd = "6373891990",
                            sdt = "099 198 37 36"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 760, DateTimeKind.Local).AddTicks(9729),
                            Email = "LeQuocThang@gmail.com",
                            Name = "Thắng",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            Surname = "Lê Quốc",
                            cmnd = "6373891990",
                            ngaysinh = new DateTime(2022, 11, 24, 21, 41, 57, 760, DateTimeKind.Local).AddTicks(9765),
                            sdt = "099 198 37 36"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 761, DateTimeKind.Local).AddTicks(338),
                            Email = "NguyenNhatTien@gmail.com",
                            Name = "Tiến",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            Surname = "Nguyễn Nhất",
                            cmnd = "6373891990",
                            ngaysinh = new DateTime(2022, 11, 24, 21, 41, 57, 761, DateTimeKind.Local).AddTicks(344),
                            sdt = "099 198 37 36"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2022, 11, 24, 21, 41, 57, 761, DateTimeKind.Local).AddTicks(385),
                            Email = "ChuMinhNghia@gmail.com",
                            Name = "Chu",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            Surname = "Minh Nghĩa",
                            cmnd = "6373891990",
                            ngaysinh = new DateTime(2022, 11, 24, 21, 41, 57, 761, DateTimeKind.Local).AddTicks(386),
                            sdt = "099 198 37 36"
                        });
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.Product", b =>
                {
                    b.HasOne("QuanLyKho.Data.Entity.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryId");

                    b.HasOne("QuanLyKho.Data.Entity.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Product")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.StoreStock", b =>
                {
                    b.HasOne("QuanLyKho.Data.Entity.Product", "Product")
                        .WithMany("StoreStock")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKho.Data.Entity.Store", "Store")
                        .WithMany("StoreStock")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.Transaction", b =>
                {
                    b.HasOne("QuanLyKho.Data.Entity.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKho.Data.Entity.Store", "ToStore")
                        .WithMany()
                        .HasForeignKey("ToStoreId");

                    b.HasOne("QuanLyKho.Data.Entity.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("ToStore");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.TransactionDetail", b =>
                {
                    b.HasOne("QuanLyKho.Data.Entity.Product", "Product")
                        .WithMany("TransactionDetail")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKho.Data.Entity.Transaction", "Transaction")
                        .WithMany("TransactionDetail")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.Product", b =>
                {
                    b.Navigation("StoreStock");

                    b.Navigation("TransactionDetail");
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.Store", b =>
                {
                    b.Navigation("StoreStock");
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.Transaction", b =>
                {
                    b.Navigation("TransactionDetail");
                });

            modelBuilder.Entity("QuanLyKho.Data.Entity.UnitOfMeasure", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
